deployment:
  replicas: 1
  strategy:
    type: RollingUpdate
    maxSurge: 1
    maxUnavailable: 0
  containers:
    - name: frigate
      image:
        repository: ghcr.io/blakeblackshear/frigate
        tag: stable
      ports:
        - name: http
          containerPort: 5000
        - name: rtsp
          containerPort: 8554
        - name: webrtc-tcp
          containerPort: 8555
          protocol: TCP
        - name: webrtc-udp
          containerPort: 8555
          protocol: UDP
      resources:
        requests:
          cpu: 0m
          memory: 0Mi
        limits:
          cpu: 12000m
          memory: 14000Mi
      volumeMounts:
        - name: storage
          mountPath: /config
          subPath: frigate/config
        - name: storage
          mountPath: /media/frigate
          subPath: frigate/media
        - name: storage
          mountPath: /tmp/cache
          subPath: shm
        - name: storage-quicksync
          mountPath: /dev/dri
      securityContext:
        privileged: true
  volumes:
    - name: storage
      type: pvc
      typeName: storage-pvc
    - name: storage-quicksync
      type: pvc
      typeName: storage-quicksync-pvc

pvcs:
  - name: storage-pvc
    storageClassName: local-path-persistent
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    volumeMode: Filesystem
  - name: storage-quicksync-pvc
    storageClassName: local-path-quicksync
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    volumeMode: Filesystem

services:
  - name: service
    type: ClusterIP
    ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: 5000
      - name: rtsp
        protocol: TCP
        port: 8554
      - name: webrtc-tcp
        protocol: TCP
        port: 8555
      - name: webrtc-udp
        protocol: UDP
        port: 8556